name: CI/CD Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t cv-parser:latest .

    - name: Login to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        script: |
          docker stop cv-parser || true
          docker rm cv-parser || true
          docker rmi cv-parser || true
          cd /home/${{ secrets.AWS_EC2_USER }}/cv-parser
          git pull origin main
          docker build -t cv-parser .
          docker run -d --name cv-parser -p 5000:5000 cv-parser
